states:
  initial:
    prompt: "Welcome to our service. How can I help you today?"
    transitions:
      - processing
      - fallback
  processing:
    prompt: "Let me help you with that."
    transitions:
      - resolution
      - escalation
  fallback:
    prompt: "Transferring to an operator."
    transitions: []
